# Specifies the default target, can set to anything
default: report

HARNESS = packetbuf_copyfrom_harness.c
LINK = $(ROOT)/os/net/packetbuf.c
ROOT = ../../../..

# Include our special CBMC build file
include ../../Makefile.include
